name = "CartesianCutCell"
uuid = "21ad27bb-7bae-4588-b189-a1a591923795"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
